# Generated by Django 4.1.11 on 2023-11-09 10:34

import app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Entry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=138)),
                ('name', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(max_length=200)),
                ('license', models.ImageField(blank=True, null=True, upload_to='users/driving')),
                ('vehicle_num', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=255)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='ID/driving')),
                ('hospital_license', models.ImageField(blank=True, null=True, upload_to='hospital_license/driving')),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', djongo.models.fields.EmbeddedField(model_container=app.models.Post)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=138)),
                ('location', models.CharField(max_length=255)),
                ('license_img', models.ImageField(blank=True, null=True, upload_to='users/hospital/')),
                ('landline', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('no_of_ambulances', models.CharField(max_length=3)),
                ('established', models.CharField(max_length=255)),
                ('supervisor_id_card', models.ImageField(blank=True, null=True, upload_to='hospital_license/hospital/')),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=100, null=True)),
                ('hospital_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('car_name', models.CharField(max_length=20)),
                ('car_number', models.CharField(max_length=10)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USER_details',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in', models.CharField(choices=[('temporarily', 'temporarily')], default='temporarily', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=138)),
                ('user', models.CharField(default='user', max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USER_Entry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=138)),
                ('phone_number', models.CharField(max_length=200)),
                ('emergency_phone_number', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
