# Generated by Django 4.1.13 on 2023-11-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('USER', 'User'), ('DRIVER', 'Driver'), ('HOSPITAL_MANAGEMENT', 'Hospital Management')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='driver_license/')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location_access', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_license', models.ImageField(blank=True, null=True, upload_to='hospital_license/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
