# Generated by Django 4.1.13 on 2023-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_userprofile_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='hospital_license',
            field=models.ImageField(blank=True, null=True, upload_to='users/hospital'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/driving'),
        ),
    ]
