# Generated by Django 4.1.13 on 2023-11-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user11_remove_userdetail_user_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User11',
        ),
    ]
