# Generated by Django 4.1.13 on 2023-11-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_driver_entry_hospital_user_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_entry',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver_entry',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='users/driving'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='license_img',
            field=models.ImageField(blank=True, null=True, upload_to='users/hospital/'),
        ),
    ]
