# Generated by Django 4.1.11 on 2023-11-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_driver_entry_hospital_user_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_entry',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='users/driving'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='license_img',
            field=models.ImageField(blank=True, null=True, upload_to='users/hospital/'),
        ),
    ]
